name: Application Kubernetes Release

on:
  push:
    tags:
      - '*'

env:
  USERNAME: ${{ github.actor }}
  CR_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    permissions: write-all
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Login GHCR
        run: echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin
      - name: Docker Build Image tags
        run: docker build -f ./deploy/Dockerfile -t "ghcr.io/$GITHUB_REPOSITORY:${{ steps.branch_name.outputs.SOURCE_TAG }}" .
      - name: Push to ghcr.io tags
        run: docker push ghcr.io/$GITHUB_REPOSITORY:${{ steps.branch_name.outputs.SOURCE_TAG }}
      - name: Docker Build Image Latest
        run: docker build -f ./deploy/Dockerfile -t "ghcr.io/$GITHUB_REPOSITORY:latest" .
      - name: Push to ghcr.io latest
        run: docker push ghcr.io/$GITHUB_REPOSITORY:latest
